version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata:
