name: Deploy to EC2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Set this to your Node.js version

      - name: Install dependencies
        run: yarn install

      # - name: Run tests
      #   run: yarn test

      - name: Decode and setup SSH key
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: $HOME/.ssh/id_rsa
          script: |
            cd /docker-nestjs-aws  # Adjust path as necessary
            git pull
            yarn install
            yarn migrate
            yarn seed
            yarn build
            yarn start:prod
